#define GLOBAL_UI_SCALE 0.95f

#define GAMEBOARD_HEIGHT_OFFSET 0.05f
#define TIMER_HEIGHT_OFFSET 0.04f
#define MISSION_HEIGHT_OFFSET 0.87f
#define MISSION_HEIGHT_TEXT_OFFSET2 0.9f
#define MISSION_HEIGHT_TEXT_OFFSET 0.95f

#define MIDDLE_WIDTH_OFFSET 0.5f
#define MIDDLE_HEIGHT_OFFSET 0.5f

#define PLAYER_WIDTH_OFFSET 0.855f
#define PLAYER_SCORE_HEIGHT_OFFSET 0.7f
#define PLAYER_LINES_HEIGHT_OFFSET 0.75f

#define ENEMY_WIDTH_OFFSET 0.145f

#define NAME_UI_OFFSET 0.12f
#define SPEECH_UI_HEIGHT_OFFSET 0.67f
#define SPEECH_TEXT_UI_HEIGHT_OFFSET 0.03f
#define AVATAR_UI_HEIGHT_OFFSET 0.37f
